[{
"ContractID": "O-ICT",
"Status" : false
},{
"ContractID": "O-IPT",
"Status" : false
},{
"ContractID": "O-PTT",
"Status" : false
},{
"ContractID": "O-SIOP",
"Status" : false
},{
"ContractID": "O-TCP",
"Status" : false
},{
"ContractID": "O-TE",
"Status" : false
},{
"ContractID": "O-THAP",
"Status" : false
},{
"ContractID": "O-TM",
"Status" : false
},{
"ContractID": "O-TP",
"Status" : false
},{
"ContractID": "O-TS",
"Status" : false
},{
"ContractID": "O-SAKC",
"Status" : false
}]